title: DAVID AFOLAYAN
#logo: asset/Retail transaction.jpg
description: I'm an analytical professional bridging data and business solutions, excelling in Data Analysis, Business Analysis, and QA Engineering. I'm passionate about delivering actionable insights that drive strategic decisions and boost performance. As an active DSN community member, I'm committed to continuous learning and applying advanced techniques to solve real-world problems.
Connect with Me : [![LinkedIn](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/afolayan-tolulope/)
[![Kaggle](https://img.shields.io/badge/Kaggle-21BBD7?style=for-the-badge&logo=kaggle&logoColor=white)](https://www.kaggle.com/davidafolayan)
[![Email](https://img.shields.io/badge/Email-D14836?style=for-the-badge&logo=gmail&logoColor=white)](mailto:david4afolayan@gmail.com)
#show_download: false
theme: jekyll-theme-minimal
css: /asset/style.css
